config/routes.rb
VRTonight::Application.routes.draw do
  devise_for :users
  root :to => 'pages#home'
  get 'newyork' => 'pages#newyork'
  get 'listyourplace' => 'pages#listyourplace'
  get 'austin' => 'pages#austin'
  get 'rockefeller23' => 'pages#rockefeller23'
  get 'rockefeller25' => 'pages#rockefeller25'
  get 'midtown40' => 'pages#midtown40'
  get 'midtown41' => 'pages#midtown41'
  get 'midtown58' => 'pages#midtown58'
  get 'inquiry' => 'inquiries#new'
  get 'austinlistyourplace' => 'pages#austinlistyourplace'
  get 'houstonlistyourplace' => 'pages#houstonlistyourplace'

  resources :inquiries, :only => [:new, :create] do
    get 'thank_you', :on => :collection
  end

end

app/models/inquiry.rb
class Inquiry 
  extend ActiveModel::Naming
  include ActiveModel::Conversion
  include ActiveModel::Validations
  include ActionView::Helpers::TextHelper
  
  attr_accessor :name, :email, :phone, :condo, :check

  validates :condo, 
            :presence => true
  
  validates :name, 
            :presence => true
  
  validates :email,
            :format => { :with => /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/ },
            :presence => true

  validates :phone,
            :length => { :minimum => 7, :maximum => 14 },
            :presence => true     

  validates :check,
            :presence => true

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def deliver
    return false unless valid?
    Pony.mail({
      :from => %("#{name}" <#{email}>),
      :reply_to => "sungho@condorentalstonight.com",
      :subject => "CondoRentalTonight Reservation",
      :body => %("#{condo}" "#{name}" <#{email}> "#{phone}" "#{check}")
    })
  end
      
  def persisted?
    false
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController

  def new
    @inquiry = Inquiry.new
  end

  def create
    @inquiry = Inquiry.new(params[:inquiry])
    if @inquiry.deliver
      render :thank_you
    else
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def action
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/inquiries/_form.html.erb
<%=simple_form_for inquiry do |f| %>

  <% if inquiry.errors.any? %>
    <ul>
      <% inquiry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  
  </br>

   <div>
    <%= f.label :condo, :label => "The name of the condo you'd like to reserve" %><br/>
    <%= f.text_field :condo %>
  </div>

  </br>

  <div>
    <%= f.label :name, :label => 'Full Name' %><br/>
    <%= f.text_field :name %>
  </div>

  </br>
  
  <div>
    <%= f.label :email, :label => 'Email' %><br/>
    <%= f.text_field :email %>
  </div>

  </br>

  <div>
    <%= f.label :phone, :label => 'Phone (including area code)' %><br/>
    <%= f.text_field :phone %>
  </div>

  </br>

  <div>
    <%= f.label :check, :label => 'Expected Check-in Time' %><br/>
    <%= f.text_field :check %>
  </div>

  <div class= "form-actions">
    <%= link_to "Back", :back, class: "btn btn-large btn-info" %>
    <%= f.submit "Next", class: "btn btn-large btn-primary" %>
  </div>
<% end %>

app/views/inquiries/_newlisting.html.erb
<%= simple_form_for inquiry do |f| %>

  <% if inquiry.errors.any? %>
    <ul>
      <% inquiry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  
  </br>

   <div>
    <%= f.label :condo, :label => "Please link us to your condo listing (Airbnb, Homeaway, VRBO, etc)." %><br/>
    <%= f.text_field :condo %>
  </div>

  <div>
    <%= f.label :name, :label => 'Full Name' %><br/>
    <%= f.text_field :name %>
  </div>
  
  <div>
    <%= f.label :email, :label => 'Email' %><br/>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :phone, :label => 'Phone (including area code)' %><br/>
    <%= f.text_field :phone %>
  </div>

  <div class= "form-actions">
    <%= f.submit "Send", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/inquiries/new.html.erb
<div class="container-fluid" style="text-align: center">
	<h1>Reservation Information</h1>
	<p>Please fill out the form below so we can pass on your reservation information to the property manager. </br>Your reservation will be complete when you complete the payment process on the next page.</p>

	<%= render 'form', :inquiry => @inquiry %>
</div>

app/views/inquiries/thank_you.html.erb
<div>
	<h1>Complete Registration</h1>
	<p>Your reservation has been sent and we'll be in touch as soon as possible.</p>
</div>

app/views/layouts/_austin_airbnb_1550763.html.erb
<div class="row-fluid">
  <div class="span4">
    <a href="https://www.airbnb.com/rooms/1550763" target="_blank"> <img src="http://i.imgur.com/npnEecz.png" alt="Bedroom"></a>
  </div>
  <div class="span8">
    <h2>Cozy 1 Bedroom Apt Downtown</h2>
    <p><i>What you'll notice first: King Size Bed</i></p>
    <p style="color: grey">1 Bedroom/1 Bath</br>Sleeps 4</p>
    <p> Located on West 3rd Street, Austin, TX 78701, United States</p>
    <p style="font-size: 17px"><strike> $149 </strike></br>
    <b style="font-size: 20px">$75</b> </br> CRTonight Price </p>
    <p>
      <a class="btn btn-info" href="https://www.airbnb.com/rooms/1550763" target="_blank">View details »</a>  <a class="btn btn-danger" href="#">Already Booked :(</a>
    </p> 
  </div>
</div>

<hr class="featurette-divider">

app/views/layouts/_austin_airbnb_718098.html.erb
<div class="row-fluid">
  <div class="span4">
    <a href="https://www.airbnb.com/rooms/718098" target="_blank"> <img src="http://i.imgur.com/8oepXHn.png" alt="Bedroom"></a>
  </div>
  <div class="span8">
    <h2>Downtown Apartment 3 blocks to 6th</h2>
    <p><i>What you'll notice first: The Open Floorplan</i></p>
    <p style="color: grey">1 Bedroom/1 Bath</br>Sleeps 4</p>
    <p> Located on Sandra Muraida Way, Austin, TX 78703, United States</p>
    <p style="font-size: 17px"><strike> $349 </strike></br>
    <b style="font-size: 20px">$200</b> </br> CRTonight Price </p>
    <p>
      <a class="btn btn-info" href="https://www.airbnb.com/rooms/718098" target="_blank">View details »</a>  <a class="btn btn-success" href="#">Book through us for the exclusive discount and no hassle reservation.</a>
    </p> 
  </div>
</div>

<hr class="featurette-divider">

app/views/layouts/_austin_airbnb_943528.html.erb
<div class="row-fluid">
  <div class="span4">
    <a href="https://www.airbnb.com/rooms/943528" target="_blank"> <img src="http://i.imgur.com/y3OIGeV.png" alt="Bedroom"></a>
  </div>
  <div class="span8">
    <h2>Beside Convention Ctr & SXSW Venues</h2>
    <p><i>What you'll notice first: The Leather Furniture</i></p>
    <p style="color: grey">1 Bedroom/1 Bath</br>Sleeps 3</p>
    <p> Located on East 4th Street, Austin, TX 78701, United States</p>
    <p style="font-size: 17px"><strike> $200 </strike></br>
    <b style="font-size: 20px">$100</b> </br> CRTonight Price </p>
    <p>
      <a class="btn btn-info" href="https://www.airbnb.com/rooms/943528" target="_blank">View details »</a>  <a class="btn btn-danger" href="#">Already Booked :(</a>
    </p> 
  </div>
</div>

<hr class="featurette-divider">

app/views/layouts/_austin_vrbo_355897.html.erb
<div class="row-fluid">
  <div class="span4">
    <a href="http://www.vrbo.com/355897#photos" target="_blank"> <img src="http://imagesus.homeaway.com/mda01/f1bc35c5-1974-4274-a64d-87d9be0194fc.1.10" alt="Bedroom"></a>
  </div>
  <div class="span8">
    <h2>Downtown Loft w/ Balcony</h2>
    <p><i>What you'll notice first: The location</i></p>
    <p style="color: grey">1 Bedroom/1 Bath</br>Sleeps 4</p>
    <p> Located across the street from the historic Driskill Hotel.</p>
    <p style="font-size: 17px"><strike> $150 </strike></br>
    <b style="font-size: 20px">$75</b> </br> CRTonight Price </p>
    <p>
      <a class="btn btn-info" href="http://www.vrbo.com/355897#" target="_blank">View details »</a>  <a class="btn btn-danger" href="#">Already Booked :(</a>
    </p> 
  </div>
</div>

<hr class="featurette-divider">

app/views/layouts/_austin_vrbo_3638416.html.erb
<div class="row-fluid">
  <div class="span4">
    <a href="http://www.vrbo.com/3638416ha#photos" target="_blank"> <img src="http://imagesus.homeaway.com/mda01/3a3c8643-e653-4bff-82f1-e13c7f874202.1.10" alt="Bedroom"></a>
  </div>
  <div class="span8">
    <h2>Unbeatable Downtown Location!</h2>
    <p><i>What you'll notice first: The Disco Ball</i></p>
    <p style="color: grey">1 Bedroom/1 Bath</br>Sleeps 4</p>
    <p> Located 2 blocks to 6th st, the warehouse district and lady bird lake</p>
    <p style="font-size: 17px"><strike> $149 </strike></br>
    <b style="font-size: 20px">$75</b> </br> CRTonight Price </p>
    <p>
      <a class="btn btn-info" href="http://www.vrbo.com/3638416ha" target="_blank">View details »</a>  <a class="btn btn-danger" href="#">Already Booked :(</a>
    </p> 
  </div>
</div>

<hr class="featurette-divider">

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="container container-static-bottom">
	<small>
	</small>
	</div>
</footer> 

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-static-top">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="brand" href="/">CRTonight</a>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li class="active"><%= link_to "Find a Place", root_path %></li>
          <li class="active"><%= link_to "List your Place", listyourplace_path %></li>
        </ul> 
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/_midtown40.erb
<div class="row-fluid">
  <div class="span4">
    <a href="http://imgur.com/a/VoWBR#0" target="blank"> <img src="http://i.imgur.com/9VS2nwz.jpg" alt="Living Room"></a>
  </div>
  <div= class="span8">
    <h2>Midtown 40</h2>
    <p>1 Bedroom 1 Bath, sleeps 6</p>
    <p>Located within 3 blocks of 53rd & 10th Ave, New York</p>
    <p><strike>$619</strike> <b>$350/night</b></p>
    <p><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i> 1 review</p>
    <p><a class="btn btn-info" href="http://www.homeaway.com/vacation-rental/p928588" target="_blank">View details »</a>  <a class="btn btn-success" href="#">Book It Now »</a></p> 
  </div>
  <hr class="featurette-divider">

app/views/layouts/_midtown40.html.erb
<div class="row-fluid">
  <div class="span4">
    <a href="/midtown40"> <img class="thumbnail" src="http://i.imgur.com/9VS2nwz.jpg" alt="Living Room"></a>
  </div>
  <div class="span8">
    <h2>Midtown 40</h2>
    <p style="color: grey">1 Bedroom/1 Bath</br>Sleeps 6</p>
    <p> Location: Midtown</p>
    <p style="font-size: 17px"><strike> $349 </strike></br>
    <b style="font-size: 20px">$175</b> </br> CRTonight Price </p>
    <p>
      <a class="btn btn-info" href="/rockefeller23" target="_blank">View details »</a>
      <a class="btn btn-danger" href="#">Already Booked :(</a>
    </p> 
  </div>
</div>
  <hr class="featurette-divider">

app/views/layouts/_midtown41.html.erb
<div class="row-fluid">
  <div class="span4">
    <a href="/midtown41"> <img class="thumbnail" src="http://i.imgur.com/zKDa4Cw.jpg" alt="Living Room"></a>
  </div>
  <div class="span8">
    <h2>Midtown 41</h2>
    <p style="color: grey">1 Bedroom/1 Bath</br>Sleeps 6</p>
    <p> Location: Midtown</p>
    <p style="font-size: 17px"><strike> $349 </strike></br>
    <b style="font-size: 20px">$175</b> </br> CRTonight Price </p>
    <p>
      <a class="btn btn-info" href="/rockefeller23" target="_blank">View details »</a>
      <a class="btn btn-danger" href="#">Already Booked :(</a>
    </p> 
  </div>
</div>
  <hr class="featurette-divider">

app/views/layouts/_midtown58.html.erb
<div class="row-fluid">
  <div class="span4">
    <a href="/midtown58"> <img class="thumbnail" src="http://i.imgur.com/dYL2hI3.jpg" alt="Living Room"></a>
  </div>
  <div class="span8">
    <h2>Midtown 58</h2>
    <p style="color: grey">1 Bedroom/1 Bath</br>Sleeps 6</p>
    <p> Location: Midtown</p>
    <p style="font-size: 17px"><strike> $349 </strike></br>
    <b style="font-size: 20px">$175</b> </br> CRTonight Price </p>
    <p>
      <a class="btn btn-info" href="/rockefeller23" target="_blank">View details »</a>
      <a class="btn btn-danger" href="#">Already Booked :(</a>
    </p> 
  </div>
</div>

app/views/layouts/_rockefeller23.html.erb
<div class="row-fluid">
  <div class="span4">
    <a href="/rockefeller23"> <img class="thumbnail" src="http://i.imgur.com/IyUzszV.jpg" alt="Living Room"></a>
  </div> 
  <div class="span8">
    <h2>Rockefeller 23</h2>
    <p style="color: grey">1 Bedroom/1 Bath</br>Sleeps 4-5</p>
    <p> Location: Midtown</p>
    <p style="font-size: 17px"><strike> $549 </strike></br>
    <b style="font-size: 20px">$299</b> </br> CRTonight Price </p>
    <a class="btn btn-info" href="/rockefeller23" target="_blank">View details »</a>  
    <a class="btn btn-success" href="inquiries/new">Book it!</a>
    </p> 
  </div>
</div>

  <hr class="featurette-divider">

app/views/layouts/_rockefeller25.html.erb
<div class="row-fluid">
  <div class="span4">
    <a href="/rockefeller25"> <img class="thumbnail" src="http://i.imgur.com/vdL51nl.jpg" alt="Bedroom"></a>
  </div>
    <div class="span8">
      <h2>Rockefeller 25</h2>
      <p style="color: grey">1 Bedroom/1 Bath</br>Sleeps 4-5</p>
      <p> Location: Midtown</p>
      <p style="font-size: 17px"><strike> $549 </strike></br>
      <b style="font-size: 20px">$299</b> </br> CRTonight Price </p>
      <p>
        <a class="btn btn-info" href="/rockefeller23" target="_blank">View details »</a>
        <a class="btn btn-danger" href="#">Already Booked :(</a>
      </p> 
  </div>
</div>
  <hr class="featurette-divider">

app/views/layouts/application.html.erb
<html>
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-6586454-6', 'condorentalstonight.com');
	  ga('send', 'pageview');

	</script>
	<head>
	  <title>CRTonight: Same Day Condo Rentals</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>	  		
	</head>
	<body>
		<%= render 'layouts/header' %>
		<%= yield %>
		<div class= "container">
			<% flash.each do |name, msg| %>
				<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
				<% end %> 
			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/pages/austin.html.erb
</br>

<h1><center>The best condos available tonight in Austin<center></h1>
 
<hr class="featurette-divider">

<div class="container">
	<%= render 'layouts/austin_airbnb_1550763' %>
	<%= render 'layouts/austin_airbnb_718098' %>
	<%= render 'layouts/austin_airbnb_943528' %>
	<%= render 'layouts/austin_vrbo_3638416' %>
	<%= render 'layouts/austin_vrbo_355897' %>
	<%= render 'layouts/austin_vrbo_3636062' %>

</div>
 
<hr class="featurette-divider">

app/views/pages/austinlistyourplace.html.erb
<div id= "listyourplace-container" class= "row-fluid">
	<div class="container" style="text-align: center">
			<div id= "listyourplace-header-container" class="container">
			<h1 id= "listyourplace-header-font">Are you passing up on free money?</h1>
			<p id= "listyourplace-subheader-font">Fill up those "one-off days" between bookings.</p>
			</div>
		</br>
			<p id="paragraph-container">Filling up just 3-4 empty nights every month could lead to an additional 36 to 48 booked nights every year. </br></br>That's over a month of extra revenue!
			</p>

		</br>
		</br>

		<h2 id="listyourplace-header2-font">Apply</h2>

		</br>
		<div class="container" style="width: 400px">
				<script type="text/javascript" src="http://form.jotform.us/jsform/33006108694148"></script>
		</div>
	</div>
</div>

app/views/pages/home.html.erb
<div id="banner-container" class="row-fluid">
	<div id="headline-container" class="container">
		<h1 id="header-font">
			<center>Book an Awesome Condo Tonight!</center>
		</h1>
		<lead>
			<center id="subheader-font">The day's best unbooked condo rentals posted at 12pm EST everyday.</center>
		</lead>
	</div>
	<center>
		<div id="choose_city" class="btn-group">
		  <a class="btn btn-large dropdown-toggle" data-toggle="dropdown" href="#">
		    Choose A City   
		    <span class="caret"></span>
		  </a>
		  <ul class="dropdown-menu">
		    <li><%= link_to "New York City, NY", newyork_path %><li>
		    <li><%= link_to "Austin, TX (Coming Soon)", root_path %><li>
		    <li><%= link_to "Houston, TX (Coming Soon)", root_path %><li>
		  </ul>
		</div>
	</center>
</div>   

app/views/pages/houston.html.erb
</br>

<h1><center>The best condos available tonight in Houston<center></h1>
 
<hr class="featurette-divider">

<div class="container">
	<%= render 'layouts/rockefeller23' %>
	<%= render 'layouts/rockefeller25' %>
	<%= render 'layouts/midtown40' %>
	<%= render 'layouts/midtown41' %>
	<%= render 'layouts/midtown58' %>   
</div>
 
<hr class="featurette-divider">

app/views/pages/houstonlistyourplace.html.erb
<div id= "listyourplace-container" class= "row-fluid">
	<div class="container" style="text-align: center">
			<div id= "listyourplace-header-container" class="container">
			<h1 id= "listyourplace-header-font">Are you passing up on free money?</h1>
			<p id= "listyourplace-subheader-font">Fill up those "one-off days" between bookings.</p>
			</div>
		</br>
			<p id="paragraph-container">Filling up just 3-4 empty nights every month could lead to an additional 36 to 48 booked nights every year. </br></br>That's over a month of extra revenue!
			</p>

		</br>
		</br>

		<h2 id="listyourplace-header2-font">Apply</h2>

		</br>
		<div class="container" style="width: 400px">
				<script type="text/javascript" src="http://form.jotform.us/jsform/33006108694148"></script>
		</div>
	</div>
</div>

app/views/pages/listyourplace.html.erb
<div id= "listyourplace-container" class= "row-fluid">
	<div class="container" style="text-align: center">
			<div id= "listyourplace-header-container" class="container">
			<h1 id= "listyourplace-header-font">Are you passing up on free money?</h1>
			<p id= "listyourplace-subheader-font">Fill up those "one-off days" between bookings.</p>
			</div>
		</br>
			<p id="paragraph-container">Filling up just 3-4 empty nights every month could lead to an additional 36 to 48 booked nights every year. </br></br>That's over a month of extra revenue!
			</p>

		</br>
		</br>

		<h2 id="listyourplace-header2-font">Apply</h2>

		</br>
		<div class="container" style="width: 400px">
				<script type="text/javascript" src="http://form.jotform.us/jsform/33006108694148"></script>
		</div>
	</div>
</div>

app/views/pages/midtown40.html.erb
</br>

<div class="container">
	<h1>Midtown 40</h1>

	<p style="color: grey">Midtown: 53rd Street between 10th and 11th Avenues</p>

</br>

<p>A cut above the rest! This Midtown Manhattan apartment leaves you a short walk from some of the boroughs most well known attractions. Whether you’re looking to relax in a quiet neighborhood park or enjoy the world famous Central Park, hangout in Times Square, admire the naval ship and fighter jets at the Intrepid Museum, or experience the different cuisines in Hell’s Kitchen, it’s all here!</p>

<p>As you walk into this gorgeous one bedroom unit, you can’t help but notice your heart skip a beat when you look through the floor-to-ceiling windows. From the comfort of the living room, you can admire the Manhattan Skyline in all it's glory, It doesn’t get much better than that! Besides the view, this unit offers top of the line kitchen appliances, a 32-inch flat screen TV with cable and Net-Flix enabled DVD player, free of charge. The gorgeous brown leather sofa folds out into a comfortable full sized bed. In the master bedroom, you will be able to continue admiring the views of the city.</p>

<p>With this location you’ll have it all! The peaceful breeze of the Hudson just a short walk to the west and the hustle and bustle of Times Square, a short 10 minute walk from your front door! If you’re a foodie, enjoy the convenience of thousands of different cuisines in your backyard – Hell’s Kitchen! Are you a fan of warships and fighter jets? Walk a few blocks to the south and you’ll be setting foot in the Intrepid Museum. Whatever it is that brings you to NYC, you’ll find it nearby without having to sacrifice a quite night when it’s time to rest up for the next day and your next big adventure in the concrete jungle!</p>
</br>

	<h2 style="font-size: 30px">Accommodations and Amenitites</h2>
		<div class="container pull-left" style="width: 400px;">
			<div style="float: left; width: 50%;">
				<ul>
          <li>Accomodates: 6</li>
          <li>Bedrooms: 1</li>
          <li>Bathrooms: 1</li>
          <li>Living Room - 2 sleeper sofas</li>
          <li>Free wifi</li>
          <li>Hair Dryer</li>
          <li>Towels Provided</li>
        </ul>
      </div>
      <div style="float: right; width: 50%;">
        <ul>
          <li>Elevator</li>
          <li>Washer/Dryer</li>
          <li>Toilet Paper</li>
          <li>Linens Provided</li>
          <li>Air Conditioning</li>
          <li>Iron & Board</li>
          <li>Heating</li>
				</ul>
			</div>
		</div>
</div>
</br>
<div class="container">
	<p style="font-size: 16px"><b>Check in: 4pm</b></p> 
	<p style="font-size: 16px"><b>Check out: 11am</b></p> 
</div>
<div class="container"> 
	<h1 style="font-size: 30px">Photos</h1>
	<ul class="thumbnails">
  <li class="span4">
    <a href="http://imgur.com/a/VoWBR#0" class="thumbnail" target="blank">
      <img data-src="#" alt="360x270" style="width: 360px; height: 270px;" src="http://i.imgur.com/9VS2nwz.jpg">
    </a>
  </li>
  <li class="span4">
    <a href="http://imgur.com/a/VoWBR#4" class="thumbnail" target="blank">
      <img data-src="holder.js/300x200" alt="360x270" style="width: 360px; height: 270px;" src="http://i.imgur.com/XpPo8II.jpg">
    </a>
  </li>
  <li class="span4">
    <a href="http://imgur.com/a/VoWBR#6" class="thumbnail" target="blank">
      <img data-src="holder.js/300x200" alt="360x270" style="width: 360px; height: 270px;" src="http://i.imgur.com/M8dtgj6.jpg">
    </a>
  </li>
    <li class="span4">
    <a href="http://imgur.com/a/VoWBR#8" class="thumbnail" target="blank">
      <img data-src="holder.js/300x200" alt="360x270" style="width: 360px; height: 270px;" src="http://i.imgur.com/IcDR2ky.jpg">
    </a>
  </li>
  <li class="span4">
    <a href="http://imgur.com/a/VoWBR#15" class="thumbnail" target="blank">
      <img data-src="holder.js/300x200" alt="360x270" style="width: 360px; height: 270px;" src="http://i.imgur.com/mSrSlSk.jpg">
    </a>
  </li>
    <li class="span4">
    <a href="http://imgur.com/a/VoWBR#17" class="thumbnail" target="blank">
      <img data-src="holder.js/300x200" alt="360x270" style="width: 360px; height: 270px;" src="http://i.imgur.com/JfKm3ar.jpg">
    </a>
   	</li>
	</ul>
</div>
<div class="container" style="padding-bottom: 30px; text-align: center;">
  <%= link_to "Back", :back, class: "btn btn-large btn-info" %>
  <a class="btn btn-large btn-danger" href="#">Already Booked :(</a>
</div>

app/views/pages/newyork.html.erb
</br>

<h1><center>The best condos available tonight in New York<center></h1>
 
<hr class="featurette-divider">

<div class="container">
	<%= render 'layouts/rockefeller23' %> 
	<%= render 'layouts/rockefeller25' %> 
	<%= render 'layouts/midtown40' %> 
	<%= render 'layouts/midtown41' %> 
	<%= render 'layouts/midtown58' %> 
</div>
 
<hr class="featurette-divider">